/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.bdd.xtext.BddDslRuntimeModule;
import dk.sdu.bdd.xtext.BddDslStandaloneSetup;
import dk.sdu.bdd.xtext.ide.BddDslIdeModule;
import dk.sdu.bdd.xtext.web.services.AstServiceDispatcher;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.util.Modules2;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BddDslWebSetup extends BddDslStandaloneSetup {
  private final IResourceBaseProvider resourceBaseProvider;

  private final AstServiceDispatcher astProvider;

  @Override
  public Injector createInjector() {
    BddDslWebModule webModule = new BddDslWebModule(this.resourceBaseProvider, this.astProvider);
    BddDslRuntimeModule _bddDslRuntimeModule = new BddDslRuntimeModule();
    BddDslIdeModule _bddDslIdeModule = new BddDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_bddDslRuntimeModule, _bddDslIdeModule, webModule));
  }

  public BddDslWebSetup(final IResourceBaseProvider resourceBaseProvider, final AstServiceDispatcher astProvider) {
    super();
    this.resourceBaseProvider = resourceBaseProvider;
    this.astProvider = astProvider;
  }
}
