/*
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.bdd.xtext.parser.antlr.internal.InternalBddDslParser;
import dk.sdu.bdd.xtext.services.BddDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BddDslParser extends AbstractAntlrParser {

	@Inject
	private BddDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBddDslParser createParser(XtextTokenStream stream) {
		return new InternalBddDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BddDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BddDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
