/*
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BddDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/bdd/xtext/parser/antlr/internal/InternalBddDsl.tokens");
	}
}
