/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl.impl;

import dk.sdu.bdd.xtext.bddDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BddDslFactoryImpl extends EFactoryImpl implements BddDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BddDslFactory init()
  {
    try
    {
      BddDslFactory theBddDslFactory = (BddDslFactory)EPackage.Registry.INSTANCE.getEFactory(BddDslPackage.eNS_URI);
      if (theBddDslFactory != null)
      {
        return theBddDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BddDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BddDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BddDslPackage.MODEL: return createModel();
      case BddDslPackage.MODEL_REF: return createModelRef();
      case BddDslPackage.DECLARATIVE_ENTITY_DEF: return createDeclarativeEntityDef();
      case BddDslPackage.IMPERATIVE_ENTITY_DEF: return createImperativeEntityDef();
      case BddDslPackage.IMPERATIVE_ACTION_DEF: return createImperativeActionDef();
      case BddDslPackage.ACTION_DEF: return createActionDef();
      case BddDslPackage.STATE_DEF: return createStateDef();
      case BddDslPackage.STATE_NAME: return createStateName();
      case BddDslPackage.PROPERTY_DEF: return createPropertyDef();
      case BddDslPackage.IMPERATIVE_STATE_DEF: return createImperativeStateDef();
      case BddDslPackage.IMPERATIVE_STATE_NAME: return createImperativeStateName();
      case BddDslPackage.IMPERATIVE_PROPERTY_DEF: return createImperativePropertyDef();
      case BddDslPackage.SCENARIO: return createScenario();
      case BddDslPackage.IMPERATIVE_SCENARIO: return createImperativeScenario();
      case BddDslPackage.DECLARATIVE_SCENARIO_STATE: return createDeclarativeScenarioState();
      case BddDslPackage.DECLARATIVE_SCENARIO_STATE_AND: return createDeclarativeScenarioStateAnd();
      case BddDslPackage.IMPERATIVE_SCENARIO_STATE: return createImperativeScenarioState();
      case BddDslPackage.IMPERATIVE_SCENARIO_STATE_AND: return createImperativeScenarioStateAnd();
      case BddDslPackage.DECLARATIVE_SCENARIO_ACTION: return createDeclarativeScenarioAction();
      case BddDslPackage.DECLARATIVE_SCENARIO_ACTION_AND: return createDeclarativeScenarioActionAnd();
      case BddDslPackage.IMPERATIVE_SCENARIO_ACTION: return createImperativeScenarioAction();
      case BddDslPackage.IMPERATIVE_SCENARIO_ACTION_AND: return createImperativeScenarioActionAnd();
      case BddDslPackage.DECLARATIVE_ENTITY_REF: return createDeclarativeEntityRef();
      case BddDslPackage.IMPERATIVE_ENTITY_REF: return createImperativeEntityRef();
      case BddDslPackage.ACTION_REF: return createActionRef();
      case BddDslPackage.IMPERATIVE_ACTION_REF: return createImperativeActionRef();
      case BddDslPackage.PROPERTY_REF: return createPropertyRef();
      case BddDslPackage.IMPERATIVE_PROPERTY_REF: return createImperativePropertyRef();
      case BddDslPackage.DECLARATIVE_ENTITY_OR_PROPERTY_REF: return createDeclarativeEntityOrPropertyRef();
      case BddDslPackage.DECLARATIVE_ENTITY_STATE_PHRASE: return createDeclarativeEntityStatePhrase();
      case BddDslPackage.DECLARATIVE_ENTITY_STATE_PHRASE_WITH_PROPERTY: return createDeclarativeEntityStatePhraseWithProperty();
      case BddDslPackage.IMPERATIVE_ENTITY_STATE_PHRASE: return createImperativeEntityStatePhrase();
      case BddDslPackage.IMPERATIVE_ENTITY_STATE_PHRASE_WITH_PROPERTY: return createImperativeEntityStatePhraseWithProperty();
      case BddDslPackage.DECLARATIVE_ENTITY_PROPERTY_STATE_PHRASE: return createDeclarativeEntityPropertyStatePhrase();
      case BddDslPackage.IMPERATIVE_ENTITY_PROPERTY_STATE_PHRASE: return createImperativeEntityPropertyStatePhrase();
      case BddDslPackage.VERB_ACTION: return createVerbAction();
      case BddDslPackage.DECLARATIVE_ENTITY_ACTION: return createDeclarativeEntityAction();
      case BddDslPackage.DECLARATIVE_ENTITY_PROPERTY_ACTION: return createDeclarativeEntityPropertyAction();
      case BddDslPackage.IMPERATIVE_VERB_ACTION: return createImperativeVerbAction();
      case BddDslPackage.IMPERATIVE_ENTITY_ACTION: return createImperativeEntityAction();
      case BddDslPackage.IMPERATIVE_ENTITY_PROPERTY_ACTION: return createImperativeEntityPropertyAction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModelRef createModelRef()
  {
    ModelRefImpl modelRef = new ModelRefImpl();
    return modelRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityDef createDeclarativeEntityDef()
  {
    DeclarativeEntityDefImpl declarativeEntityDef = new DeclarativeEntityDefImpl();
    return declarativeEntityDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityDef createImperativeEntityDef()
  {
    ImperativeEntityDefImpl imperativeEntityDef = new ImperativeEntityDefImpl();
    return imperativeEntityDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeActionDef createImperativeActionDef()
  {
    ImperativeActionDefImpl imperativeActionDef = new ImperativeActionDefImpl();
    return imperativeActionDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActionDef createActionDef()
  {
    ActionDefImpl actionDef = new ActionDefImpl();
    return actionDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateDef createStateDef()
  {
    StateDefImpl stateDef = new StateDefImpl();
    return stateDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateName createStateName()
  {
    StateNameImpl stateName = new StateNameImpl();
    return stateName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PropertyDef createPropertyDef()
  {
    PropertyDefImpl propertyDef = new PropertyDefImpl();
    return propertyDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeStateDef createImperativeStateDef()
  {
    ImperativeStateDefImpl imperativeStateDef = new ImperativeStateDefImpl();
    return imperativeStateDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeStateName createImperativeStateName()
  {
    ImperativeStateNameImpl imperativeStateName = new ImperativeStateNameImpl();
    return imperativeStateName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativePropertyDef createImperativePropertyDef()
  {
    ImperativePropertyDefImpl imperativePropertyDef = new ImperativePropertyDefImpl();
    return imperativePropertyDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Scenario createScenario()
  {
    ScenarioImpl scenario = new ScenarioImpl();
    return scenario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenario createImperativeScenario()
  {
    ImperativeScenarioImpl imperativeScenario = new ImperativeScenarioImpl();
    return imperativeScenario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeScenarioState createDeclarativeScenarioState()
  {
    DeclarativeScenarioStateImpl declarativeScenarioState = new DeclarativeScenarioStateImpl();
    return declarativeScenarioState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeScenarioStateAnd createDeclarativeScenarioStateAnd()
  {
    DeclarativeScenarioStateAndImpl declarativeScenarioStateAnd = new DeclarativeScenarioStateAndImpl();
    return declarativeScenarioStateAnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioState createImperativeScenarioState()
  {
    ImperativeScenarioStateImpl imperativeScenarioState = new ImperativeScenarioStateImpl();
    return imperativeScenarioState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioStateAnd createImperativeScenarioStateAnd()
  {
    ImperativeScenarioStateAndImpl imperativeScenarioStateAnd = new ImperativeScenarioStateAndImpl();
    return imperativeScenarioStateAnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeScenarioAction createDeclarativeScenarioAction()
  {
    DeclarativeScenarioActionImpl declarativeScenarioAction = new DeclarativeScenarioActionImpl();
    return declarativeScenarioAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeScenarioActionAnd createDeclarativeScenarioActionAnd()
  {
    DeclarativeScenarioActionAndImpl declarativeScenarioActionAnd = new DeclarativeScenarioActionAndImpl();
    return declarativeScenarioActionAnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioAction createImperativeScenarioAction()
  {
    ImperativeScenarioActionImpl imperativeScenarioAction = new ImperativeScenarioActionImpl();
    return imperativeScenarioAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioActionAnd createImperativeScenarioActionAnd()
  {
    ImperativeScenarioActionAndImpl imperativeScenarioActionAnd = new ImperativeScenarioActionAndImpl();
    return imperativeScenarioActionAnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityRef createDeclarativeEntityRef()
  {
    DeclarativeEntityRefImpl declarativeEntityRef = new DeclarativeEntityRefImpl();
    return declarativeEntityRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityRef createImperativeEntityRef()
  {
    ImperativeEntityRefImpl imperativeEntityRef = new ImperativeEntityRefImpl();
    return imperativeEntityRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActionRef createActionRef()
  {
    ActionRefImpl actionRef = new ActionRefImpl();
    return actionRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeActionRef createImperativeActionRef()
  {
    ImperativeActionRefImpl imperativeActionRef = new ImperativeActionRefImpl();
    return imperativeActionRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PropertyRef createPropertyRef()
  {
    PropertyRefImpl propertyRef = new PropertyRefImpl();
    return propertyRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativePropertyRef createImperativePropertyRef()
  {
    ImperativePropertyRefImpl imperativePropertyRef = new ImperativePropertyRefImpl();
    return imperativePropertyRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityOrPropertyRef createDeclarativeEntityOrPropertyRef()
  {
    DeclarativeEntityOrPropertyRefImpl declarativeEntityOrPropertyRef = new DeclarativeEntityOrPropertyRefImpl();
    return declarativeEntityOrPropertyRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityStatePhrase createDeclarativeEntityStatePhrase()
  {
    DeclarativeEntityStatePhraseImpl declarativeEntityStatePhrase = new DeclarativeEntityStatePhraseImpl();
    return declarativeEntityStatePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityStatePhraseWithProperty createDeclarativeEntityStatePhraseWithProperty()
  {
    DeclarativeEntityStatePhraseWithPropertyImpl declarativeEntityStatePhraseWithProperty = new DeclarativeEntityStatePhraseWithPropertyImpl();
    return declarativeEntityStatePhraseWithProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityStatePhrase createImperativeEntityStatePhrase()
  {
    ImperativeEntityStatePhraseImpl imperativeEntityStatePhrase = new ImperativeEntityStatePhraseImpl();
    return imperativeEntityStatePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityStatePhraseWithProperty createImperativeEntityStatePhraseWithProperty()
  {
    ImperativeEntityStatePhraseWithPropertyImpl imperativeEntityStatePhraseWithProperty = new ImperativeEntityStatePhraseWithPropertyImpl();
    return imperativeEntityStatePhraseWithProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityPropertyStatePhrase createDeclarativeEntityPropertyStatePhrase()
  {
    DeclarativeEntityPropertyStatePhraseImpl declarativeEntityPropertyStatePhrase = new DeclarativeEntityPropertyStatePhraseImpl();
    return declarativeEntityPropertyStatePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityPropertyStatePhrase createImperativeEntityPropertyStatePhrase()
  {
    ImperativeEntityPropertyStatePhraseImpl imperativeEntityPropertyStatePhrase = new ImperativeEntityPropertyStatePhraseImpl();
    return imperativeEntityPropertyStatePhrase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VerbAction createVerbAction()
  {
    VerbActionImpl verbAction = new VerbActionImpl();
    return verbAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityAction createDeclarativeEntityAction()
  {
    DeclarativeEntityActionImpl declarativeEntityAction = new DeclarativeEntityActionImpl();
    return declarativeEntityAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclarativeEntityPropertyAction createDeclarativeEntityPropertyAction()
  {
    DeclarativeEntityPropertyActionImpl declarativeEntityPropertyAction = new DeclarativeEntityPropertyActionImpl();
    return declarativeEntityPropertyAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeVerbAction createImperativeVerbAction()
  {
    ImperativeVerbActionImpl imperativeVerbAction = new ImperativeVerbActionImpl();
    return imperativeVerbAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityAction createImperativeEntityAction()
  {
    ImperativeEntityActionImpl imperativeEntityAction = new ImperativeEntityActionImpl();
    return imperativeEntityAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeEntityPropertyAction createImperativeEntityPropertyAction()
  {
    ImperativeEntityPropertyActionImpl imperativeEntityPropertyAction = new ImperativeEntityPropertyActionImpl();
    return imperativeEntityPropertyAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BddDslPackage getBddDslPackage()
  {
    return (BddDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BddDslPackage getPackage()
  {
    return BddDslPackage.eINSTANCE;
  }

} //BddDslFactoryImpl
