/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl.impl;

import dk.sdu.bdd.xtext.bddDsl.BddDslPackage;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenario;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenarioAction;
import dk.sdu.bdd.xtext.bddDsl.ImperativeScenarioState;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Imperative Scenario</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.impl.ImperativeScenarioImpl#getPreState <em>Pre State</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.impl.ImperativeScenarioImpl#getAction <em>Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.impl.ImperativeScenarioImpl#getPostState <em>Post State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ImperativeScenarioImpl extends MinimalEObjectImpl.Container implements ImperativeScenario
{
  /**
   * The cached value of the '{@link #getPreState() <em>Pre State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreState()
   * @generated
   * @ordered
   */
  protected ImperativeScenarioState preState;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected ImperativeScenarioAction action;

  /**
   * The cached value of the '{@link #getPostState() <em>Post State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPostState()
   * @generated
   * @ordered
   */
  protected ImperativeScenarioState postState;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImperativeScenarioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BddDslPackage.Literals.IMPERATIVE_SCENARIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioState getPreState()
  {
    return preState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPreState(ImperativeScenarioState newPreState, NotificationChain msgs)
  {
    ImperativeScenarioState oldPreState = preState;
    preState = newPreState;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE, oldPreState, newPreState);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPreState(ImperativeScenarioState newPreState)
  {
    if (newPreState != preState)
    {
      NotificationChain msgs = null;
      if (preState != null)
        msgs = ((InternalEObject)preState).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE, null, msgs);
      if (newPreState != null)
        msgs = ((InternalEObject)newPreState).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE, null, msgs);
      msgs = basicSetPreState(newPreState, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE, newPreState, newPreState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioAction getAction()
  {
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAction(ImperativeScenarioAction newAction, NotificationChain msgs)
  {
    ImperativeScenarioAction oldAction = action;
    action = newAction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__ACTION, oldAction, newAction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAction(ImperativeScenarioAction newAction)
  {
    if (newAction != action)
    {
      NotificationChain msgs = null;
      if (action != null)
        msgs = ((InternalEObject)action).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__ACTION, null, msgs);
      if (newAction != null)
        msgs = ((InternalEObject)newAction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__ACTION, null, msgs);
      msgs = basicSetAction(newAction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__ACTION, newAction, newAction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImperativeScenarioState getPostState()
  {
    return postState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPostState(ImperativeScenarioState newPostState, NotificationChain msgs)
  {
    ImperativeScenarioState oldPostState = postState;
    postState = newPostState;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE, oldPostState, newPostState);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPostState(ImperativeScenarioState newPostState)
  {
    if (newPostState != postState)
    {
      NotificationChain msgs = null;
      if (postState != null)
        msgs = ((InternalEObject)postState).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE, null, msgs);
      if (newPostState != null)
        msgs = ((InternalEObject)newPostState).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE, null, msgs);
      msgs = basicSetPostState(newPostState, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE, newPostState, newPostState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE:
        return basicSetPreState(null, msgs);
      case BddDslPackage.IMPERATIVE_SCENARIO__ACTION:
        return basicSetAction(null, msgs);
      case BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE:
        return basicSetPostState(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE:
        return getPreState();
      case BddDslPackage.IMPERATIVE_SCENARIO__ACTION:
        return getAction();
      case BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE:
        return getPostState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE:
        setPreState((ImperativeScenarioState)newValue);
        return;
      case BddDslPackage.IMPERATIVE_SCENARIO__ACTION:
        setAction((ImperativeScenarioAction)newValue);
        return;
      case BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE:
        setPostState((ImperativeScenarioState)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE:
        setPreState((ImperativeScenarioState)null);
        return;
      case BddDslPackage.IMPERATIVE_SCENARIO__ACTION:
        setAction((ImperativeScenarioAction)null);
        return;
      case BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE:
        setPostState((ImperativeScenarioState)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BddDslPackage.IMPERATIVE_SCENARIO__PRE_STATE:
        return preState != null;
      case BddDslPackage.IMPERATIVE_SCENARIO__ACTION:
        return action != null;
      case BddDslPackage.IMPERATIVE_SCENARIO__POST_STATE:
        return postState != null;
    }
    return super.eIsSet(featureID);
  }

} //ImperativeScenarioImpl
