/*
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.ui.tests;

import com.google.inject.Injector;
import dk.sdu.bdd.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BddDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("dk.sdu.bdd.xtext.BddDsl");
	}

}
