/*
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBddDslScopeProvider extends DelegatingScopeProvider {
}
