/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarative Entity Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntity <em>Entity</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getActionRef <em>Action Ref</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getPreposition <em>Preposition</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntity2 <em>Entity2</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction()
 * @model
 * @generated
 */
public interface DeclarativeEntityAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_Entity()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Action Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Ref</em>' containment reference.
   * @see #setActionRef(ActionRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_ActionRef()
   * @model containment="true"
   * @generated
   */
  ActionRef getActionRef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getActionRef <em>Action Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Ref</em>' containment reference.
   * @see #getActionRef()
   * @generated
   */
  void setActionRef(ActionRef value);

  /**
   * Returns the value of the '<em><b>Preposition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preposition</em>' attribute.
   * @see #setPreposition(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_Preposition()
   * @model
   * @generated
   */
  String getPreposition();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getPreposition <em>Preposition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preposition</em>' attribute.
   * @see #getPreposition()
   * @generated
   */
  void setPreposition(String value);

  /**
   * Returns the value of the '<em><b>Entity2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2</em>' containment reference.
   * @see #setEntity2(DeclarativeEntityOrPropertyRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getDeclarativeEntityAction_Entity2()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityOrPropertyRef getEntity2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.DeclarativeEntityAction#getEntity2 <em>Entity2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2</em>' containment reference.
   * @see #getEntity2()
   * @generated
   */
  void setEntity2(DeclarativeEntityOrPropertyRef value);

} // DeclarativeEntityAction
