/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Imperative Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getPreState <em>Pre State</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getAction <em>Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getPostState <em>Post State</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeScenario()
 * @model
 * @generated
 */
public interface ImperativeScenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Pre State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State</em>' containment reference.
   * @see #setPreState(ImperativeScenarioState)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeScenario_PreState()
   * @model containment="true"
   * @generated
   */
  ImperativeScenarioState getPreState();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getPreState <em>Pre State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State</em>' containment reference.
   * @see #getPreState()
   * @generated
   */
  void setPreState(ImperativeScenarioState value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(ImperativeScenarioAction)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeScenario_Action()
   * @model containment="true"
   * @generated
   */
  ImperativeScenarioAction getAction();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(ImperativeScenarioAction value);

  /**
   * Returns the value of the '<em><b>Post State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post State</em>' containment reference.
   * @see #setPostState(ImperativeScenarioState)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getImperativeScenario_PostState()
   * @model containment="true"
   * @generated
   */
  ImperativeScenarioState getPostState();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ImperativeScenario#getPostState <em>Post State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post State</em>' containment reference.
   * @see #getPostState()
   * @generated
   */
  void setPostState(ImperativeScenarioState value);

} // ImperativeScenario
