/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.ModelRef#getModelRef <em>Model Ref</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getModelRef()
 * @model
 * @generated
 */
public interface ModelRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Model Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Ref</em>' reference.
   * @see #setModelRef(Model)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getModelRef_ModelRef()
   * @model
   * @generated
   */
  Model getModelRef();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.ModelRef#getModelRef <em>Model Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Ref</em>' reference.
   * @see #getModelRef()
   * @generated
   */
  void setModelRef(Model value);

} // ModelRef
