/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getScenarioName <em>Scenario Name</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getPreStateE <em>Pre State E</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative1 <em>Imperative1</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getActionE <em>Action E</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative2 <em>Imperative2</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getPreStateE1 <em>Pre State E1</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative3 <em>Imperative3</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Scenario Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario Name</em>' attribute.
   * @see #setScenarioName(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_ScenarioName()
   * @model
   * @generated
   */
  String getScenarioName();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getScenarioName <em>Scenario Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario Name</em>' attribute.
   * @see #getScenarioName()
   * @generated
   */
  void setScenarioName(String value);

  /**
   * Returns the value of the '<em><b>Pre State E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State E</em>' containment reference.
   * @see #setPreStateE(DeclarativeScenarioState)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_PreStateE()
   * @model containment="true"
   * @generated
   */
  DeclarativeScenarioState getPreStateE();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getPreStateE <em>Pre State E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State E</em>' containment reference.
   * @see #getPreStateE()
   * @generated
   */
  void setPreStateE(DeclarativeScenarioState value);

  /**
   * Returns the value of the '<em><b>Imperative1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imperative1</em>' containment reference.
   * @see #setImperative1(ImperativeScenario)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_Imperative1()
   * @model containment="true"
   * @generated
   */
  ImperativeScenario getImperative1();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative1 <em>Imperative1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imperative1</em>' containment reference.
   * @see #getImperative1()
   * @generated
   */
  void setImperative1(ImperativeScenario value);

  /**
   * Returns the value of the '<em><b>Action E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action E</em>' containment reference.
   * @see #setActionE(DeclarativeScenarioAction)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_ActionE()
   * @model containment="true"
   * @generated
   */
  DeclarativeScenarioAction getActionE();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getActionE <em>Action E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action E</em>' containment reference.
   * @see #getActionE()
   * @generated
   */
  void setActionE(DeclarativeScenarioAction value);

  /**
   * Returns the value of the '<em><b>Imperative2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imperative2</em>' containment reference.
   * @see #setImperative2(ImperativeScenario)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_Imperative2()
   * @model containment="true"
   * @generated
   */
  ImperativeScenario getImperative2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative2 <em>Imperative2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imperative2</em>' containment reference.
   * @see #getImperative2()
   * @generated
   */
  void setImperative2(ImperativeScenario value);

  /**
   * Returns the value of the '<em><b>Pre State E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State E1</em>' containment reference.
   * @see #setPreStateE1(DeclarativeScenarioState)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_PreStateE1()
   * @model containment="true"
   * @generated
   */
  DeclarativeScenarioState getPreStateE1();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getPreStateE1 <em>Pre State E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre State E1</em>' containment reference.
   * @see #getPreStateE1()
   * @generated
   */
  void setPreStateE1(DeclarativeScenarioState value);

  /**
   * Returns the value of the '<em><b>Imperative3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imperative3</em>' containment reference.
   * @see #setImperative3(ImperativeScenario)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getScenario_Imperative3()
   * @model containment="true"
   * @generated
   */
  ImperativeScenario getImperative3();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.Scenario#getImperative3 <em>Imperative3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imperative3</em>' containment reference.
   * @see #getImperative3()
   * @generated
   */
  void setImperative3(ImperativeScenario value);

} // Scenario
