/**
 * generated by Xtext 2.32.0
 */
package dk.sdu.bdd.xtext.bddDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getAction <em>Action</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition <em>Preposition</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity <em>Entity</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition2 <em>Preposition2</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity2 <em>Entity2</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition3 <em>Preposition3</em>}</li>
 *   <li>{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity3 <em>Entity3</em>}</li>
 * </ul>
 *
 * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction()
 * @model
 * @generated
 */
public interface VerbAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(ActionRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Action()
   * @model containment="true"
   * @generated
   */
  ActionRef getAction();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(ActionRef value);

  /**
   * Returns the value of the '<em><b>Preposition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preposition</em>' attribute.
   * @see #setPreposition(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Preposition()
   * @model
   * @generated
   */
  String getPreposition();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition <em>Preposition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preposition</em>' attribute.
   * @see #getPreposition()
   * @generated
   */
  void setPreposition(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference.
   * @see #setEntity(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity <em>Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' containment reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Preposition2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preposition2</em>' attribute.
   * @see #setPreposition2(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Preposition2()
   * @model
   * @generated
   */
  String getPreposition2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition2 <em>Preposition2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preposition2</em>' attribute.
   * @see #getPreposition2()
   * @generated
   */
  void setPreposition2(String value);

  /**
   * Returns the value of the '<em><b>Entity2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity2</em>' containment reference.
   * @see #setEntity2(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity2()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity2();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity2 <em>Entity2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity2</em>' containment reference.
   * @see #getEntity2()
   * @generated
   */
  void setEntity2(DeclarativeEntityRef value);

  /**
   * Returns the value of the '<em><b>Preposition3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preposition3</em>' attribute.
   * @see #setPreposition3(String)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Preposition3()
   * @model
   * @generated
   */
  String getPreposition3();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getPreposition3 <em>Preposition3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preposition3</em>' attribute.
   * @see #getPreposition3()
   * @generated
   */
  void setPreposition3(String value);

  /**
   * Returns the value of the '<em><b>Entity3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity3</em>' containment reference.
   * @see #setEntity3(DeclarativeEntityRef)
   * @see dk.sdu.bdd.xtext.bddDsl.BddDslPackage#getVerbAction_Entity3()
   * @model containment="true"
   * @generated
   */
  DeclarativeEntityRef getEntity3();

  /**
   * Sets the value of the '{@link dk.sdu.bdd.xtext.bddDsl.VerbAction#getEntity3 <em>Entity3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity3</em>' containment reference.
   * @see #getEntity3()
   * @generated
   */
  void setEntity3(DeclarativeEntityRef value);

} // VerbAction
